import React,{useMemo,useState} from 'react';
import { useApp } from '../../context/AppContext';
import { teacherKpi } from '../../utils/management';
import { pathId, pushRoute } from '../../utils/deepLink';
import { Award, BookOpen, CalendarCheck, ClipboardCheck, Eye, Link2, UserRound } from 'lucide-react';
export const Teacher360Module:React.FC=()=>{
 const {allMembers,assignments,teacherPlans,lessonPlans,observations,meetings,trainings,auditLogs,setNotification}=useApp();
 const initial=pathId('teachers'); const [id,setId]=useState(initial&&allMembers.some(m=>m.id===initial)?initial:(allMembers[0]?.id||''));
 const m=allMembers.find(x=>x.id===id)||allMembers[0];
 const kpi=useMemo(()=>m?teacherKpi(m,{teacherPlans,lessonPlans,observations,meetings,trainings}):null,[m,teacherPlans,lessonPlans,observations,meetings,trainings]);
 if(!m||!kpi)return <div className="p-6 text-sm text-slate-500">Chưa có giáo viên.</div>;
 const asg=assignments.filter(a=>a.teacherId===m.id); const logs=auditLogs.filter(l=>l.actorId===m.id||l.targetId===m.id).sort((a,b)=>b.timestamp.localeCompare(a.timestamp)).slice(0,8);
 const copy=async()=>{pushRoute('teacher-360',m.id,true); await navigator.clipboard.writeText(window.location.href); setNotification({type:'success',message:'Đã sao chép liên kết hồ sơ 360°.'});};
 return <div className="space-y-5">
  <div className="bg-white border border-slate-200 rounded-xl p-5 flex flex-wrap justify-between gap-4"><div><div className="flex items-center gap-2"><UserRound className="w-5 h-5 text-blue-600"/><h1 className="text-xl font-bold">Hồ sơ 360° giáo viên</h1></div><p className="text-xs text-slate-500 mt-1">Một điểm nhìn: phân công → hồ sơ → giáo án → dự giờ → nhiệm vụ → KPI → dấu vết.</p></div><div className="flex gap-2"><select value={m.id} onChange={e=>{setId(e.target.value);pushRoute('teacher-360',e.target.value)}} className="border rounded-lg px-3 py-2 text-xs bg-white">{allMembers.map(x=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select><button onClick={copy} className="border rounded-lg px-3 py-2 text-xs font-semibold flex items-center gap-1"><Link2 className="w-3.5 h-3.5"/>Sao chép link</button></div></div>
  <div className="grid md:grid-cols-4 gap-3"><div className="md:col-span-1 bg-blue-600 text-white rounded-xl p-5"><div className="text-xs text-blue-100">KPI minh chứng</div><div className="text-5xl font-black mt-2">{kpi.total}</div><div className="text-xs mt-1">/ 100 điểm</div><div className="border-t border-blue-400 mt-4 pt-3 text-xs space-y-1"><div className="font-bold">{m.displayName}</div><div>{m.subject}</div><div>{m.qualifications||'Chưa cập nhật trình độ'}</div><div>{asg.map(a=>a.className).filter(Boolean).join(', ')||'Chưa phân công lớp'}</div></div></div>
   <div className="md:col-span-3 grid sm:grid-cols-2 lg:grid-cols-5 gap-3">{kpi.evidence.map((e,i)=>{const I=[CalendarCheck,BookOpen,Eye,ClipboardCheck,Award][i];return <div key={e.label} className="bg-white border rounded-xl p-4"><I className="w-4 h-4 text-blue-600"/><div className="text-xs font-bold mt-2">{e.label}</div><div className="text-xl font-black mt-1">{e.score}<span className="text-xs font-medium text-slate-400">/{e.max}</span></div><div className="text-[11px] text-slate-500 mt-1">{e.value}</div></div>})}</div></div>
  <div className="grid lg:grid-cols-2 gap-5"><div className="bg-white border rounded-xl p-5"><h2 className="font-bold text-sm mb-3">Minh chứng cấu thành KPI</h2><div className="space-y-3">{kpi.evidence.map(e=><details key={e.label} className="border rounded-lg p-3"><summary className="cursor-pointer text-xs font-semibold flex justify-between"><span>{e.label}</span><span>{e.score}/{e.max}</span></summary><div className="mt-2 text-[11px] text-slate-600">{e.refs.length?e.refs.map((r,i)=><div key={i} className="py-1 border-t first:border-0">• {r}</div>):<i>Chưa có minh chứng.</i>}</div></details>)}</div></div>
   <div className="bg-white border rounded-xl p-5"><h2 className="font-bold text-sm mb-3">Hoạt động & dấu vết gần đây</h2>{logs.length?<div className="space-y-2">{logs.map(l=><div key={l.id} className="border-l-2 border-blue-200 pl-3 py-1"><div className="text-xs font-semibold">{l.action}</div><div className="text-[11px] text-slate-500">{new Date(l.timestamp).toLocaleString('vi-VN')} · {l.details}</div></div>)}</div>:<div className="text-xs text-slate-500">Chưa có nhật ký liên quan.</div>}</div></div>
 </div>
}
