import type {
  Member,
  SchoolClass,
  Assignment,
  DepartmentConfig,
  DepartmentPlan,
  TeacherPlan,
  LessonPlan,
  Meeting,
  LessonStudyCycle,
  ObservationRecord,
  SpecialTopic,
  TrainingRecord,
  InitiativeRecord,
  MemberInvitation,
  AccessRequest,
  AcademicCalendarMilestone,
  MathCompetencyTag,
  CurriculumTopic,
  ObservationCriterionItem,
  Question,
  SharedDocument,
  SkknTopic,
} from '../types';

export const SAMPLE_CALENDAR_MILESTONES: AcademicCalendarMilestone[] = [
  { id: 'm-01', name: 'Lễ Khai giảng năm học mới & Ổn định nền nếp', term: 'HK1', week: 1, dateStart: '2026-09-05', dateEnd: '2026-09-06', type: 'meeting', description: 'Toàn trường khai giảng, tổ chức họp tổ chuyên môn đầu năm.' },
  { id: 'm-02', name: 'Khảo sát chất lượng đầu năm môn Toán K10, 11, 12', term: 'HK1', week: 3, dateStart: '2026-09-18', dateEnd: '2026-09-20', type: 'exam', description: 'Đánh giá năng lực đầu vào và phân loại đối tượng bồi dưỡng.' },
  { id: 'm-03', name: 'Kiểm tra Đánh giá Giữa Học kỳ 1 (Toán 10, 11, 12)', term: 'HK1', week: 9, dateStart: '2026-10-30', dateEnd: '2026-11-04', type: 'exam', description: 'Đề chung toàn khối, cấu trúc 3 phần theo định dạng 2025.' },
  { id: 'm-04', name: 'Thao giảng chuyên đề CV 5512 chào mừng ngày 20/11', term: 'HK1', week: 11, dateStart: '2026-11-15', dateEnd: '2026-11-20', type: 'meeting', description: 'Tổ chức sinh hoạt chuyên môn theo nghiên cứu bài học.' },
  { id: 'm-05', name: 'Kiểm tra Đánh giá Cuối Học kỳ 1', term: 'HK1', week: 18, dateStart: '2026-12-25', dateEnd: '2026-12-30', type: 'exam', description: 'Thi tập trung, chấm chéo hai vòng, báo cáo ma trận đặc tả.' },
  { id: 'm-06', name: 'Sơ kết Học kỳ 1 & Triển khai kế hoạch Học kỳ 2', term: 'HK1', week: 18, dateStart: '2027-01-05', dateEnd: '2027-01-06', type: 'meeting', description: 'Đánh giá kết quả xếp loại và tiến độ thực hiện chương trình.' },
  { id: 'm-07', name: 'Bắt đầu chương trình Học kỳ 2', term: 'HK2', week: 19, dateStart: '2027-01-08', dateEnd: '2027-01-08', type: 'buffer', description: 'Khởi động HK2, phân phối tuần 19-35.' },
  { id: 'm-08', name: 'Nghỉ Tết Nguyên Đán Đinh Mùi', term: 'HK2', week: 23, dateStart: '2027-02-10', dateEnd: '2027-02-21', type: 'holiday', description: 'Nghỉ lễ theo quy định UBND tỉnh và Bộ GD&ĐT.' },
  { id: 'm-09', name: 'Kiểm tra Đánh giá Giữa Học kỳ 2', term: 'HK2', week: 27, dateStart: '2027-03-24', dateEnd: '2027-03-28', type: 'exam', description: 'Đánh giá định kỳ giữa kỳ 2.' },
  { id: 'm-10', name: 'Thi thử Tốt nghiệp THPT đợt 1 Khối 12', term: 'HK2', week: 32, dateStart: '2027-04-20', dateEnd: '2027-04-22', type: 'exam', description: 'Chuẩn format Bộ GD&ĐT 2025, rà soát kiến thức toàn diện.' },
  { id: 'm-11', name: 'Kiểm tra Cuối Học kỳ 2 & Xét tốt nghiệp tạm thời', term: 'HK2', week: 35, dateStart: '2027-05-15', dateEnd: '2027-05-20', type: 'exam', description: 'Hoàn thành chương trình 35 tuần, khóa sổ học bạ điện tử.' },
  { id: 'm-12', name: 'Tổng kết năm học 2026-2027 & Bàn giao hồ sơ chuyên môn', term: 'CaNam', week: 35, dateStart: '2027-05-28', dateEnd: '2027-05-30', type: 'meeting', description: 'Lễ bế giảng, khen thưởng GV-HS và lưu trữ số hóa hồ sơ tổ.' },
];

export const SAMPLE_COMPETENCY_TAGS: MathCompetencyTag[] = [
  {
    id: 'tag-nl1',
    code: 'NL1',
    name: 'Tư duy và lập luận toán học',
    description: 'Thực hiện các thao tác tư duy so sánh, phân tích, tổng hợp, suy luận hợp lý và logic.',
    components: ['Nhận biết mối liên hệ logic', 'Đưa ra suy luận quy nạp và suy diễn', 'Chứng minh hoặc bác bỏ mệnh đề toán học'],
  },
  {
    id: 'tag-nl2',
    code: 'NL2',
    name: 'Mô hình hóa toán học',
    description: 'Chuyển đổi bài toán thực tiễn sang ngôn ngữ toán học, giải quyết và đối chiếu kết quả thực tế.',
    components: ['Thiết lập mô hình toán từ ngữ cảnh thực tiễn', 'Giải quyết bài toán trong mô hình đã lập', 'Đánh giá tính hợp lý và giải thích kết quả thực tế'],
  },
  {
    id: 'tag-nl3',
    code: 'NL3',
    name: 'Giải quyết vấn đề toán học',
    description: 'Xác định tình huống có vấn đề, đề xuất giải pháp, lựa chọn và thực hiện phương án tối ưu.',
    components: ['Phát hiện tình huống cần giải quyết', 'Lựa chọn phương pháp và công cụ thích hợp', 'Đánh giá tính đúng đắn và hiệu quả của lời giải'],
  },
  {
    id: 'tag-nl4',
    code: 'NL4',
    name: 'Giao tiếp toán học',
    description: 'Sử dụng ngôn ngữ, ký hiệu toán học để trình bày, diễn đạt, tranh luận ý tưởng khoa học.',
    components: ['Đọc hiểu văn bản và bảng biểu toán học', 'Trình bày lập luận rõ ràng, mạch lạc', 'Phản biện và tiếp nhận góp ý có tính xây dựng'],
  },
  {
    id: 'tag-nl5',
    code: 'NL5',
    name: 'Sử dụng công cụ và phương tiện học toán',
    description: 'Sử dụng máy tính cầm tay, phần mềm hình học (GeoGebra), bảng tính, ứng dụng vẽ đồ thị.',
    components: ['Sử dụng thành thạo máy tính cầm tay (Casio fx-580VN X, fx-880BTG)', 'Mô phỏng 2D/3D bằng GeoGebra', 'Ứng dụng CNTT trong tra cứu và biểu diễn dữ liệu'],
  },
];

export const SAMPLE_CURRICULUM_TOPICS: CurriculumTopic[] = [
  // Khối 12
  { id: 'top-12-01', grade: 12, title: 'Ứng dụng đạo hàm để khảo sát và vẽ đồ thị hàm số', strand: 'Đại số & Giải tích', estimatedPeriods: 22, objectives: 'Đơn điệu, cực trị, GTLN-GTNN, tiệm cận, vẽ đồ thị và giải quyết bài toán tối ưu thực tiễn.' },
  { id: 'top-12-02', grade: 12, title: 'Vectơ và hệ tọa độ trong không gian Oxyz', strand: 'Hình học & Đo lường', estimatedPeriods: 16, objectives: 'Vectơ trong không gian, tọa độ điểm và vectơ Oxyz, tích vô hướng và ứng dụng.' },
  { id: 'top-12-03', grade: 12, title: 'Các số đặc trưng đo mức độ phân tán của mẫu ghép nhóm', strand: 'Thống kê & Xác suất', estimatedPeriods: 12, objectives: 'Khoảng biến thiên, khoảng tứ phân vị, phương sai và độ lệch chuẩn của số liệu ghép nhóm.' },
  { id: 'top-12-04', grade: 12, title: 'Nguyên hàm, Tích phân và Ứng dụng hình học', strand: 'Đại số & Giải tích', estimatedPeriods: 22, objectives: 'Khái niệm, tính chất nguyên hàm, tích phân, tính diện tích hình phẳng và thể tích vật thể.' },
  { id: 'top-12-05', grade: 12, title: 'Phương pháp tọa độ trong không gian Oxyz (Mặt phẳng, Đường thẳng, Mặt cầu)', strand: 'Hình học & Đo lường', estimatedPeriods: 20, objectives: 'Viết phương trình mặt phẳng, đường thẳng, mặt cầu và vị trí tương đối.' },
  { id: 'top-12-06', grade: 12, title: 'Xác suất có điều kiện và Công thức Bayes', strand: 'Thống kê & Xác suất', estimatedPeriods: 14, objectives: 'Xác suất có điều kiện, công thức xác suất toàn phần, công thức Bayes và mô hình dự báo.' },
  { id: 'top-12-07', grade: 12, title: 'Chuyên đề học tập Toán 12 (Ứng dụng toán học thực tế & Lý thuyết đồ thị)', strand: 'Chuyên đề học tập', estimatedPeriods: 35, objectives: 'Vận dụng toán học giải quyết vấn đề quy hoạch tuyến tính và mạng lưới đồ thị.' },
  // Khối 11
  { id: 'top-11-01', grade: 11, title: 'Hàm số lượng giác và Phương trình lượng giác', strand: 'Đại số & Giải tích', estimatedPeriods: 16, objectives: 'Công thức lượng giác, hàm số lượng giác cơ bản, phương trình lượng giác.' },
  { id: 'top-11-02', grade: 11, title: 'Dãy số, Cấp số cộng và Cấp số nhân', strand: 'Đại số & Giải tích', estimatedPeriods: 14, objectives: 'Công thức số hạng tổng quát, tính tổng n số hạng đầu tiên và bài toán tài chính.' },
  { id: 'top-11-03', grade: 11, title: 'Giới hạn và Hàm số liên tục', strand: 'Đại số & Giải tích', estimatedPeriods: 14, objectives: 'Giới hạn dãy số, giới hạn hàm số, định lý giá trị trung gian và tính liên tục.' },
  { id: 'top-11-04', grade: 11, title: 'Đường thẳng và Mặt phẳng trong không gian, Quan hệ song song', strand: 'Hình học & Đo lường', estimatedPeriods: 18, objectives: 'Đại cương hình không gian, hai đường song song, đường song song mặt, hai mặt song song.' },
  { id: 'top-11-05', grade: 11, title: 'Quan hệ vuông góc trong không gian', strand: 'Hình học & Đo lường', estimatedPeriods: 18, objectives: 'Đường vuông góc mặt, hai mặt phẳng vuông góc, khoảng cách và góc trong không gian.' },
  // Khối 10
  { id: 'top-10-01', grade: 10, title: 'Mệnh đề và Tập hợp', strand: 'Đại số & Giải tích', estimatedPeriods: 10, objectives: 'Mệnh đề toán học, các phép toán trên tập hợp số thực, biểu đồ Ven.' },
  { id: 'top-10-02', grade: 10, title: 'Bất phương trình và Hệ bất phương trình bậc nhất hai ẩn', strand: 'Đại số & Giải tích', estimatedPeriods: 10, objectives: 'Biểu diễn miền nghiệm và giải quyết bài toán tối ưu kinh tế đơn giản.' },
  { id: 'top-10-03', grade: 10, title: 'Hàm số bậc hai và Đồ thị', strand: 'Đại số & Giải tích', estimatedPeriods: 14, objectives: 'Tọa độ đỉnh, trục đối xứng, sự biến thiên và dấu của tam thức bậc hai.' },
  { id: 'top-10-04', grade: 10, title: 'Hệ thức lượng trong tam giác và Vectơ trong mặt phẳng', strand: 'Hình học & Đo lường', estimatedPeriods: 20, objectives: 'Định lý sin, cosin, công thức diện tích tam giác, tích vô hướng và ứng dụng.' },
];

export const SAMPLE_OBSERVATION_CRITERIA: ObservationCriterionItem[] = [
  {
    id: 'crit-01',
    group: 'KeHoach',
    groupName: 'I. Kế hoạch và tài liệu dạy học',
    name: '1. Mức độ phù hợp của chuỗi hoạt động học với mục tiêu, nội dung và phương pháp dạy học',
    indicators: ['Chuỗi hoạt động thể hiện rõ tiến trình 4 bước (Khởi động - Hình thành kiến thức - Luyện tập - Vận dụng).', 'Mục tiêu rõ ràng về phẩm chất và 5 thành phần năng lực toán học.'],
    maxScore: 2.0,
  },
  {
    id: 'crit-02',
    group: 'KeHoach',
    groupName: 'I. Kế hoạch và tài liệu dạy học',
    name: '2. Mức độ rõ ràng của mục tiêu, nội dung, kĩ thuật tổ chức và sản phẩm cần đạt của mỗi nhiệm vụ học tập',
    indicators: ['Nội dung câu hỏi, bài tập cụ thể, vừa sức với đối tượng học sinh.', 'Mô tả rõ sản phẩm học tập kỳ vọng (bảng phụ, vở ghi, phát biểu).'],
    maxScore: 2.0,
  },
  {
    id: 'crit-03',
    group: 'KeHoach',
    groupName: 'I. Kế hoạch và tài liệu dạy học',
    name: '3. Mức độ phù hợp của thiết bị dạy học và học liệu được sử dụng',
    indicators: ['Ứng dụng hiệu quả GeoGebra, máy tính cầm tay, phiếu học tập hoặc máy chiếu tương tác.', 'Học liệu toán học chính xác, mang tính gợi mở tư duy.'],
    maxScore: 2.0,
  },
  {
    id: 'crit-04',
    group: 'KeHoach',
    groupName: 'I. Kế hoạch và tài liệu dạy học',
    name: '4. Mức độ hợp lí của phương án kiểm tra, đánh giá trong quá trình dạy học',
    indicators: ['Đánh giá thường xuyên quá trình giải toán của học sinh.', 'Có tiêu chí/rubric đánh giá rõ ràng cho bài tập vận dụng.'],
    maxScore: 2.0,
  },
  {
    id: 'crit-05',
    group: 'GiaoVien',
    groupName: 'II. Hoạt động của giáo viên',
    name: '5. Mức độ sinh động, hấp dẫn của phương pháp và hình thức chuyển giao nhiệm vụ học tập',
    indicators: ['Chuyển giao nhiệm vụ rõ ràng, học sinh hiểu rõ việc cần làm.', 'Tạo hứng thú, kích thích tò mò khám phá quy luật toán học.'],
    maxScore: 2.0,
  },
  {
    id: 'crit-06',
    group: 'GiaoVien',
    groupName: 'II. Hoạt động của giáo viên',
    name: '6. Khả năng theo dõi, quan sát, phát hiện kịp thời những khó khăn của học sinh',
    indicators: ['Bao quát lớp tốt, phát hiện học sinh gặp bế tắc khi biến đổi hoặc suy luận.', 'Di chuyển hỗ trợ các nhóm đúng lúc, đúng chỗ.'],
    maxScore: 2.0,
  },
  {
    id: 'crit-07',
    group: 'GiaoVien',
    groupName: 'II. Hoạt động của giáo viên',
    name: '7. Mức độ phù hợp, hiệu quả của các biện pháp hỗ trợ và khuyến khích học sinh hợp tác',
    indicators: ['Gợi mở bằng câu hỏi phụ thay vì làm hộ học sinh.', 'Khuyến khích học sinh tranh luận, phản biện toán học.'],
    maxScore: 2.0,
  },
  {
    id: 'crit-08',
    group: 'GiaoVien',
    groupName: 'II. Hoạt động của giáo viên',
    name: '8. Mức độ chính xác, hiệu quả của việc tổng hợp, phân tích, đánh giá kết quả hoạt động và thảo luận',
    indicators: ['Chuẩn hóa kiến thức toán học chính xác tuyệt đối, chốt định lý/công thức rõ ràng.', 'Khắc sâu sai lầm thường gặp khi bấm máy tính hoặc biến đổi.'],
    maxScore: 2.0,
  },
  {
    id: 'crit-09',
    group: 'HocSinh',
    groupName: 'III. Hoạt động của học sinh',
    name: '9. Khả năng tiếp nhận và sẵn sàng thực hiện nhiệm vụ học tập của học sinh trong lớp',
    indicators: ['Học sinh chủ động mở SGK, lấy dụng cụ, ghi chép và bắt tay làm việc.', 'Không có hiện tượng học sinh ngoài cuộc hoặc mất tập trung.'],
    maxScore: 2.0,
  },
  {
    id: 'crit-10',
    group: 'HocSinh',
    groupName: 'III. Hoạt động của học sinh',
    name: '10. Mức độ tích cực, chủ động, sáng tạo, hợp tác của học sinh trong thực hiện nhiệm vụ',
    indicators: ['Tích cực trao đổi nhóm, phân công vẽ hình, tính toán rõ ràng.', 'Có học sinh tìm ra cách giải ngắn gọn, sáng tạo.'],
    maxScore: 2.0,
  },
  {
    id: 'crit-11',
    group: 'HocSinh',
    groupName: 'III. Hoạt động của học sinh',
    name: '11. Mức độ tham gia tích cực của học sinh trong trình bày, trao đổi, thảo luận',
    indicators: ['Tự tin lên bảng thuyết trình phương pháp giải bài toán.', 'Biết đặt câu hỏi chất vấn nhóm bạn và bảo vệ quan điểm logic.'],
    maxScore: 2.0,
  },
  {
    id: 'crit-12',
    group: 'HocSinh',
    groupName: 'III. Hoạt động của học sinh',
    name: '12. Mức độ đúng đắn, chính xác, phù hợp của kết quả thực hiện nhiệm vụ học tập',
    indicators: ['Học sinh hoàn thành sản phẩm học tập đúng thời hạn quy định.', 'Đại đa số nắm vững kiến thức trọng tâm và làm đúng bài tập cơ bản.'],
    maxScore: 2.0,
  },
];

export const SAMPLE_INVITATIONS: MemberInvitation[] = [
  {
    id: 'inv-01',
    email: 'giaovien.moi@thpt.edu.vn',
    displayName: 'Thầy Nguyễn Văn An',
    role: 'teacher',
    subject: 'Toán',
    status: 'pending',
    invitedBy: 'ThS. Lê Quốc Dũng',
    invitedAt: '2026-09-10T08:00:00Z',
  },
  {
    id: 'inv-02',
    email: 'tin.thpt@edu.vn',
    displayName: 'Cô Hoàng Thu Hà',
    role: 'teacher',
    subject: 'Tin học',
    status: 'accepted',
    invitedBy: 'ThS. Lê Quốc Dũng',
    invitedAt: '2026-09-02T10:00:00Z',
    acceptedAt: '2026-09-03T09:30:00Z',
  },
];

export const SAMPLE_ACCESS_REQUESTS: AccessRequest[] = [
  {
    id: 'req-01',
    email: 'nguyenhuutoan@gmail.com',
    displayName: 'Nguyễn Hữu Toàn',
    reason: 'Tôi là giáo viên Toán hợp đồng mới chuyển về trường, cần truy cập phân phối chương trình và kế hoạch bài dạy.',
    requestedAt: '2026-09-18T14:20:00Z',
    status: 'pending',
  },
];

export const SAMPLE_DEPARTMENT_CONFIG: DepartmentConfig = {
  id: 'dept-toan-01',
  schoolName: 'Trường THPT Chuyên & Thực nghiệm Nguyễn Du',
  departmentName: 'Tổ Toán – Tin học',
  academicYear: '2026-2027',
  currentTerm: 'HK1',
  startDate: '2026-09-05',
  endDate: '2027-05-28',
  weeksCount: 35,
  standardPeriods: 17,
  notes: 'Áp dụng theo Chương trình GDPT 2018 cho cả 3 khối 10, 11, 12 (Định mức chuẩn GV THPT: 17 tiết/tuần theo TT 28/2009/TT-BGDĐT).',
  calendarMilestones: SAMPLE_CALENDAR_MILESTONES,
  academicCalendar: SAMPLE_CALENDAR_MILESTONES,
  competencyTags: SAMPLE_COMPETENCY_TAGS,
  curriculumTopics: SAMPLE_CURRICULUM_TOPICS,
  observationCriteria: SAMPLE_OBSERVATION_CRITERIA,
  externalLinks: {
    examAndQuestionBankUrl: 'https://dinhcaotritue.com',
    sharedDocumentsDriveUrl: 'https://drive.google.com',
  },
};

export const SAMPLE_MEMBERS: Member[] = [
  {
    id: 'gv-01',
    email: 'thuyetdung@gmail.com', // Admin & Tổ trưởng
    displayName: 'ThS. Lê Quốc Dũng',
    role: 'head',
    qualifications: 'Thạc sĩ Toán Giải tích',
    subject: 'Toán',
    phone: '0912345678',
    status: 'active',
    joinedAt: '2020-09-01',
    periodsPerWeek: 14, // Tổ trưởng THPT giảm 3 tiết: 17 - 3 = 14 tiết/tuần
  },
  {
    id: 'gv-02',
    email: 'maiphuong.toan@thpt.edu.vn',
    displayName: 'ThS. Trần Thị Mai Phương',
    role: 'deputy',
    qualifications: 'Thạc sĩ Lý luận & PPDH Toán',
    subject: 'Toán',
    phone: '0987654321',
    status: 'active',
    joinedAt: '2021-08-15',
    periodsPerWeek: 16, // Tổ phó THPT giảm 1 tiết: 17 - 1 = 16 tiết/tuần
  },
  {
    id: 'gv-03',
    email: 'hoangnam.toan@thpt.edu.vn',
    displayName: 'Thầy Hoàng Văn Nam',
    role: 'teacher',
    qualifications: 'Cử nhân ĐH Sư phạm Toán',
    subject: 'Toán',
    phone: '0933112233',
    status: 'active',
    joinedAt: '2022-09-01',
    periodsPerWeek: 13, // GV kiêm chủ nhiệm 10A2 giảm 4 tiết: 17 - 4 = 13 tiết/tuần
  },
  {
    id: 'gv-04',
    email: 'thuylinh.toan@thpt.edu.vn',
    displayName: 'Cô Phạm Thùy Linh',
    role: 'teacher',
    qualifications: 'Cử nhân ĐH Sư phạm Toán',
    subject: 'Toán',
    phone: '0944223344',
    status: 'active',
    joinedAt: '2023-01-10',
    periodsPerWeek: 13, // GV kiêm chủ nhiệm 10A1 giảm 4 tiết: 17 - 4 = 13 tiết/tuần
  },
  {
    id: 'gv-05',
    email: 'minhtuan.toan@thpt.edu.vn',
    displayName: 'ThS. Đặng Minh Tuấn',
    role: 'teacher',
    qualifications: 'Thạc sĩ Đại số & Lý thuyết số',
    subject: 'Toán',
    phone: '0905566778',
    status: 'active',
    joinedAt: '2019-09-01',
    periodsPerWeek: 17, // Định mức chuẩn GV THPT: 17 tiết/tuần
  },
  {
    id: 'gv-06',
    email: 'ngocanh.tin@thpt.edu.vn',
    displayName: 'Cô Vũ Ngọc Ánh',
    role: 'teacher',
    qualifications: 'Cử nhân Toán - Tin học',
    subject: 'Toán - Tin',
    phone: '0977889900',
    status: 'active',
    joinedAt: '2024-09-01',
    periodsPerWeek: 13, // GV kiêm chủ nhiệm 11A2 giảm 4 tiết: 17 - 4 = 13 tiết/tuần
  },
];

export const SAMPLE_CLASSES: SchoolClass[] = [
  { id: 'cls-10A1', grade: 10, name: '10A1', studentCount: 42, homeroomTeacher: 'Cô Phạm Thùy Linh' },
  { id: 'cls-10A2', grade: 10, name: '10A2', studentCount: 40, homeroomTeacher: 'Thầy Hoàng Văn Nam' },
  { id: 'cls-11A1', grade: 11, name: '11A1', studentCount: 38, homeroomTeacher: 'ThS. Trần Thị Mai Phương' },
  { id: 'cls-11A2', grade: 11, name: '11A2', studentCount: 39, homeroomTeacher: 'Cô Vũ Ngọc Ánh' },
  { id: 'cls-12A1', grade: 12, name: '12A1', studentCount: 41, homeroomTeacher: 'ThS. Đặng Minh Tuấn' },
];

export const SAMPLE_ASSIGNMENTS: Assignment[] = [
  { id: 'asg-1', teacherId: 'gv-01', teacherName: 'ThS. Lê Quốc Dũng', classId: 'cls-12A1', className: '12A1', grade: 12, subject: 'Toán', periodsPerWeek: 4, duties: 'Tổ trưởng, Ôn thi tốt nghiệp', term: 'HK1', academicYear: '2026-2027' },
  { id: 'asg-2', teacherId: 'gv-02', teacherName: 'ThS. Trần Thị Mai Phương', classId: 'cls-11A1', className: '11A1', grade: 11, subject: 'Toán', periodsPerWeek: 4, duties: 'Tổ phó, Chủ nhiệm 11A1', term: 'HK1', academicYear: '2026-2027' },
  { id: 'asg-3', teacherId: 'gv-03', teacherName: 'Thầy Hoàng Văn Nam', classId: 'cls-10A2', className: '10A2', grade: 10, subject: 'Toán', periodsPerWeek: 4, duties: 'Chủ nhiệm 10A2', term: 'HK1', academicYear: '2026-2027' },
  { id: 'asg-4', teacherId: 'gv-04', teacherName: 'Cô Phạm Thùy Linh', classId: 'cls-10A1', className: '10A1', grade: 10, subject: 'Toán', periodsPerWeek: 4, duties: 'Chủ nhiệm 10A1', term: 'HK1', academicYear: '2026-2027' },
  { id: 'asg-5', teacherId: 'gv-05', teacherName: 'ThS. Đặng Minh Tuấn', classId: 'cls-12A1', className: '12A1', grade: 12, subject: 'Chuyên đề học tập Toán 12', periodsPerWeek: 3, duties: 'Bồi dưỡng HSG Toán', term: 'HK1', academicYear: '2026-2027' },
  { id: 'asg-6', teacherId: 'gv-06', teacherName: 'Cô Vũ Ngọc Ánh', classId: 'cls-11A2', className: '11A2', grade: 11, subject: 'Toán', periodsPerWeek: 4, duties: 'Chủ nhiệm 11A2', term: 'HK1', academicYear: '2026-2027' },
];


export const SAMPLE_DEPARTMENT_PLAN: DepartmentPlan = {
  id: 'dplan-2026-12',
  grade: 12,
  academicYear: '2026-2027',
  title: 'Kế hoạch dạy học môn Toán Khối 12 – Năm học 2026-2027 (Phụ lục I CV 5512)',
  status: 'approved',
  version: 2,
  generalSituation: 'Học sinh khối 12 học theo Chương trình GDPT 2018; chuẩn bị tham gia Kỳ thi Tốt nghiệp THPT theo định dạng mới từ năm 2025. Thiết bị đầy đủ máy chiếu, phòng máy tính nối mạng internet, học liệu số GeoGebra 3D.',
  distribution: [
    // HỌC KỲ 1 (Tuần 1 - 18: 72 tiết)
    { id: 'dist-1', order: 1, week: 1, topicTitle: 'Tính đơn điệu và cực trị của hàm số (Tiết 1-4)', periods: 4, objectives: 'Nhận biết tính đơn điệu của hàm số thông qua dấu đạo hàm cấp một. Tìm cực trị của hàm số.', equipment: 'Máy chiếu, phiếu học tập', location: 'Lớp học', status: 'completed', dateTaught: '2026-09-08' },
    { id: 'dist-2', order: 2, week: 2, topicTitle: 'Giá trị lớn nhất và nhỏ nhất của hàm số (Tiết 5-8)', periods: 4, objectives: 'Tính GTLN, GTNN trên đoạn và khoảng; giải quyết các bài toán tối ưu trong thực tiễn.', equipment: 'Phần mềm GeoGebra', location: 'Lớp học', status: 'completed', dateTaught: '2026-09-15' },
    { id: 'dist-3', order: 3, week: 3, topicTitle: 'Đường tiệm cận của đồ thị hàm số (Tiết 9-12)', periods: 4, objectives: 'Tìm tiệm cận đứng, tiệm cận ngang và tiệm cận xiên của đồ thị hàm số phân thức.', equipment: 'Bảng phụ, phiếu bài tập', location: 'Lớp học', status: 'completed', dateTaught: '2026-09-22' },
    { id: 'dist-4', order: 4, week: 4, topicTitle: 'Khảo sát sự biến thiên và vẽ đồ thị hàm số (Tiết 13-16)', periods: 4, objectives: 'Vẽ đồ thị hàm đa thức bậc ba, hàm phân thức hữu tỉ. Ứng dụng giải toán thực tế.', equipment: 'GeoGebra minh họa đồ thị', location: 'Lớp học', status: 'completed', dateTaught: '2026-09-29' },
    { id: 'dist-5', order: 5, week: 5, topicTitle: 'Ứng dụng đạo hàm giải bài toán thực tế & Bài tập cuối Chương I (Tiết 17-20)', periods: 4, objectives: 'Mô hình hóa các bài toán kinh tế, vật lý, sinh học sử dụng đạo hàm.', equipment: 'Máy tính Casio fx-580VN X', location: 'Lớp học', status: 'in_progress', dateTaught: '2026-10-06' },
    { id: 'dist-6', order: 6, week: 6, topicTitle: 'Vectơ và các phép toán trong không gian (Tiết 21-24)', periods: 4, objectives: 'Quy tắc hình hộp, tích vô hướng của hai vectơ trong không gian, góc giữa hai vectơ.', equipment: 'Mô hình không gian, GeoGebra 3D', location: 'Lớp học', status: 'planned' },
    { id: 'dist-7', order: 7, week: 7, topicTitle: 'Tọa độ của vectơ và điểm trong không gian Oxyz (Tiết 25-28)', periods: 4, objectives: 'Hệ trục tọa độ Oxyz, tọa độ điểm, tọa độ vectơ, độ dài vectơ và khoảng cách giữa 2 điểm.', equipment: 'Phần mềm GeoGebra 3D', location: 'Lớp học', status: 'planned' },
    { id: 'dist-8', order: 8, week: 8, topicTitle: 'Biểu thức tọa độ của các phép toán vectơ & Ôn tập Giữa HK1 (Tiết 29-32)', periods: 4, objectives: 'Cộng, trừ, nhân với số, tích vô hướng trong hệ tọa độ Oxyz.', equipment: 'Phiếu học tập ma trận đề', location: 'Lớp học', status: 'planned' },
    { id: 'dist-9', order: 9, week: 9, topicTitle: 'Kiểm tra Đánh giá Giữa Học kỳ 1 & Chữa bài kiểm tra (Tiết 33-36)', periods: 4, objectives: 'Đánh giá định kỳ theo cấu trúc 3 phần mới Bộ GD&ĐT (90 phút). Chữa bài và khắc phục sai lầm.', equipment: 'Đề kiểm tra in ấn, đáp án số', location: 'Lớp học', status: 'planned' },
    { id: 'dist-10', order: 10, week: 10, topicTitle: 'Khoảng biến thiên và khoảng tứ phân vị của mẫu ghép nhóm (Tiết 37-40)', periods: 4, objectives: 'Xác định khoảng biến thiên, tứ phân vị, giải thích ý nghĩa độ phân tán dữ liệu.', equipment: 'Bảng số liệu thực tiễn', location: 'Lớp học', status: 'planned' },
    { id: 'dist-11', order: 11, week: 11, topicTitle: 'Phương sai và độ lệch chuẩn của mẫu số liệu ghép nhóm (Tiết 41-44)', periods: 4, objectives: 'Tính phương sai, độ lệch chuẩn bằng máy tính cầm tay, so sánh độ ổn định.', equipment: 'Máy tính Casio fx-880BTG', location: 'Lớp học', status: 'planned' },
    { id: 'dist-12', order: 12, week: 12, topicTitle: 'Thực hành tính toán thống kê và bài tập cuối Chương III (Tiết 45-48)', periods: 4, objectives: 'Vận dụng xử lý số liệu dự báo thời tiết, kết quả học tập và tài chính.', equipment: 'Phòng máy tính / Excel', location: 'Phòng máy', status: 'planned' },
    { id: 'dist-13', order: 13, week: 13, topicTitle: 'Khái niệm nguyên hàm và tính chất cơ bản (Tiết 49-52)', periods: 4, objectives: 'Định nghĩa nguyên hàm, các tính chất cơ bản, bảng nguyên hàm các hàm số sơ cấp.', equipment: 'Bảng phụ công thức', location: 'Lớp học', status: 'planned' },
    { id: 'dist-14', order: 14, week: 14, topicTitle: 'Phương pháp tìm nguyên hàm (đổi biến số, từng phần) (Tiết 53-56)', periods: 4, objectives: 'Kỹ thuật đổi biến số dạng đơn giản, công thức nguyên hàm từng phần.', equipment: 'Phiếu rèn luyện kỹ năng', location: 'Lớp học', status: 'planned' },
    { id: 'dist-15', order: 15, week: 15, topicTitle: 'Định nghĩa và tính chất của tích phân (Tiết 57-60)', periods: 4, objectives: 'Khái niệm tích phân từ bài toán diện tích hình thang cong, công thức Newton-Leibniz.', equipment: 'Mô hình trực quan GeoGebra', location: 'Lớp học', status: 'planned' },
    { id: 'dist-16', order: 16, week: 16, topicTitle: 'Các phương pháp tính tích phân (Tiết 61-64)', periods: 4, objectives: 'Phương pháp đổi biến số và tích phân từng phần.', equipment: 'Phiếu học tập', location: 'Lớp học', status: 'planned' },
    { id: 'dist-17', order: 17, week: 17, topicTitle: 'Ôn tập tổng hợp kiến thức Học kỳ 1 (Tiết 65-68)', periods: 4, objectives: 'Hệ thống hóa kiến thức Hàm số, Tọa độ không gian, Thống kê và Nguyên hàm.', equipment: 'Sơ đồ tư duy, đề cương ôn tập', location: 'Lớp học', status: 'planned' },
    { id: 'dist-18', order: 18, week: 18, topicTitle: 'Kiểm tra Đánh giá Cuối Học kỳ 1 & Trả bài (Tiết 69-72)', periods: 4, objectives: 'Đánh giá định kỳ cuối HK1 (90 phút). Đánh giá mức độ đạt chuẩn chuẩn đầu ra.', equipment: 'Đề thi chuẩn hóa', location: 'Lớp học', status: 'planned' },

    // HỌC KỲ 2 (Tuần 19 - 35: 68 tiết)
    { id: 'dist-19', order: 19, week: 19, topicTitle: 'Ứng dụng hình học của tích phân: Tính diện tích hình phẳng (Tiết 73-76)', periods: 4, objectives: 'Công thức tính diện tích hình phẳng giới hạn bởi các đường cong.', equipment: 'GeoGebra minh họa miền phẳng', location: 'Lớp học', status: 'planned' },
    { id: 'dist-20', order: 20, week: 20, topicTitle: 'Ứng dụng tích phân: Tính thể tích vật thể và khối tròn xoay (Tiết 77-80)', periods: 4, objectives: 'Tính thể tích vật thể cắt bởi mặt phẳng vuông góc, thể tích tròn xoay quanh trục Ox.', equipment: 'Mô hình vật thể 3D', location: 'Lớp học', status: 'planned' },
    { id: 'dist-21', order: 21, week: 21, topicTitle: 'Phương trình mặt phẳng trong không gian Oxyz (Tiết 81-84)', periods: 4, objectives: 'Vectơ pháp tuyến, phương trình tổng quát của mặt phẳng, điều kiện song song và vuông góc.', equipment: 'Phần mềm GeoGebra 3D', location: 'Lớp học', status: 'planned' },
    { id: 'dist-22', order: 22, week: 22, topicTitle: 'Khoảng cách từ điểm đến mặt phẳng & Góc giữa hai mặt phẳng (Tiết 85-88)', periods: 4, objectives: 'Công thức tính khoảng cách, góc và các bài toán thực tiễn về kiến trúc mái nhà.', equipment: 'Hình ảnh thực tiễn công trình', location: 'Lớp học', status: 'planned' },
    { id: 'dist-23', order: 23, week: 23, topicTitle: 'Phương trình đường thẳng trong không gian Oxyz (Tiết 89-92)', periods: 4, objectives: 'Vectơ chỉ phương, phương trình tham số, phương trình chính tắc của đường thẳng.', equipment: 'GeoGebra 3D', location: 'Lớp học', status: 'planned' },
    { id: 'dist-24', order: 24, week: 24, topicTitle: 'Vị trí tương đối giữa hai đường thẳng, đường thẳng và mặt phẳng (Tiết 93-96)', periods: 4, objectives: 'Xác định giao điểm, quan hệ chéo nhau, song song, cắt nhau, vuông góc.', equipment: 'Phiếu học tập', location: 'Lớp học', status: 'planned' },
    { id: 'dist-25', order: 25, week: 25, topicTitle: 'Phương trình mặt cầu trong không gian (Tiết 97-100)', periods: 4, objectives: 'Phương trình chính tắc của mặt cầu tâm I bán kính R, vị trí tương đối với mặt phẳng.', equipment: 'Mô hình quả địa cầu', location: 'Lớp học', status: 'planned' },
    { id: 'dist-26', order: 26, week: 26, topicTitle: 'Xác suất có điều kiện (Tiết 101-104)', periods: 4, objectives: 'Định nghĩa xác suất có điều kiện, quy tắc nhân xác suất cho hai biến cố ngẫu nhiên.', equipment: 'Sơ đồ cây xác suất', location: 'Lớp học', status: 'planned' },
    { id: 'dist-27', order: 27, week: 27, topicTitle: 'Kiểm tra Đánh giá Giữa Học kỳ 2 & Chữa bài (Tiết 105-108)', periods: 4, objectives: 'Đánh giá định kỳ giữa HK2. Khắc sâu kỹ năng tính xác suất và phương trình Oxyz.', equipment: 'Đề kiểm tra 90 phút', location: 'Lớp học', status: 'planned' },
    { id: 'dist-28', order: 28, week: 28, topicTitle: 'Công thức xác suất toàn phần và công thức Bayes (Tiết 109-112)', periods: 4, objectives: 'Thiết lập công thức xác suất toàn phần, công thức Bayes trong xét nghiệm y tế và chuẩn đoán.', equipment: 'Bảng số liệu thực tiễn', location: 'Lớp học', status: 'planned' },
    { id: 'dist-29', order: 29, week: 29, topicTitle: 'Bài tập vận dụng xác suất trong thực tiễn & Ôn tập Chương VI (Tiết 113-116)', periods: 4, objectives: 'Giải quyết các bài toán kiểm định chất lượng, rủi ro bảo hiểm, mô hình Bayes.', equipment: 'Phiếu học tập', location: 'Lớp học', status: 'planned' },
    { id: 'dist-30', order: 30, week: 30, topicTitle: 'Ôn tập chuyên đề: Hàm số, Đạo hàm và Tích phân nâng cao (Tiết 117-120)', periods: 4, objectives: 'Hệ thống hóa câu hỏi phân loại vận dụng - vận dụng cao chuẩn cấu trúc 2025.', equipment: 'Bộ đề thi minh họa 2025', location: 'Lớp học', status: 'planned' },
    { id: 'dist-31', order: 31, week: 31, topicTitle: 'Ôn tập chuyên đề: Hình học Oxyz và các bài toán mô hình thực tế (Tiết 121-124)', periods: 4, objectives: 'Kỹ năng gắn hệ trục tọa độ vào vật thể kiến trúc, tàu bay, vệ tinh quỹ đạo.', equipment: 'GeoGebra 3D', location: 'Lớp học', status: 'planned' },
    { id: 'dist-32', order: 32, week: 32, topicTitle: 'Thi thử Tốt nghiệp THPT cấp trường & Rèn luyện kỹ năng làm bài (Tiết 125-128)', periods: 4, objectives: 'Tập dượt thi thử theo quy chế thi tốt nghiệp, rèn chiến thuật làm bài trắc nghiệm 3 phần.', equipment: 'Phiếu trả lời trắc nghiệm chuẩn', location: 'Lớp học', status: 'planned' },
    { id: 'dist-33', order: 33, week: 33, topicTitle: 'Phân tích ma trận đề thi thử, khắc phục điểm nghẽn kiến thức (Tiết 129-132)', periods: 4, objectives: 'Phân tích phổ điểm, hướng dẫn chống bẫy trắc nghiệm Đúng/Sai và Trả lời ngắn.', equipment: 'Báo cáo phổ điểm phân tích', location: 'Lớp học', status: 'planned' },
    { id: 'dist-34', order: 34, week: 34, topicTitle: 'Rà soát chuẩn kiến thức kỹ năng toàn diện Toán 12 (Tiết 133-136)', periods: 4, objectives: 'Hệ thống hóa toàn bộ công thức cốt lõi 35 tuần học.', equipment: 'Sổ tay công thức số hóa', location: 'Lớp học', status: 'planned' },
    { id: 'dist-35', order: 35, week: 35, topicTitle: 'Kiểm tra Đánh giá Cuối Học kỳ 2 & Tổng kết năm học (Tiết 137-140)', periods: 4, objectives: 'Kiểm tra cuối kỳ 2. Đánh giá xếp loại học lực, hoàn thiện hồ sơ tổ chuyên môn.', equipment: 'Đề kiểm tra, hồ sơ sổ điểm', location: 'Lớp học', status: 'planned' },
  ],
  periodicEvaluations: [
    { name: 'Kiểm tra Giữa Học kỳ 1', duration: 90, week: 9, format: 'Trắc nghiệm theo định dạng TN THPT 2025 (12 câu TN, 4 câu Đ/S, 6 câu TLN)' },
    { name: 'Kiểm tra Cuối Học kỳ 1', duration: 90, week: 18, format: 'Trắc nghiệm định dạng 2025 kết hợp câu hỏi mô hình hóa thực tiễn' },
    { name: 'Kiểm tra Giữa Học kỳ 2', duration: 90, week: 27, format: 'Trắc nghiệm định dạng 2025 trọng tâm Oxyz và Tích phân' },
    { name: 'Kiểm tra Cuối Học kỳ 2', duration: 90, week: 35, format: 'Trắc nghiệm tổng hợp toàn bộ chương trình 35 tuần' },
  ],
  createdBy: 'ThS. Lê Quốc Dũng',
  approvedBy: 'Ban Giám Hiệu (TS. Nguyễn Văn Bình)',
  updatedAt: '2026-09-08T15:00:00Z',
  versionHistory: [
    {
      version: 1,
      updatedAt: '2026-08-25T10:00:00Z',
      updatedBy: 'ThS. Lê Quốc Dũng',
      changeSummary: 'Bản dự thảo phân phối chương trình Toán 12 ban đầu (140 tiết/35 tuần)',
      status: 'submitted',
      comment: 'Kính gửi Ban Giám hiệu phê duyệt phân phối chương trình môn Toán Khối 12.',
      dataSnapshot: {
        title: 'Kế hoạch dạy học môn Toán Khối 12 (Dự thảo v1)',
        weeksCount: 35,
        totalPeriods: 140,
        distributionCount: 35,
      },
    },
    {
      version: 2,
      updatedAt: '2026-09-08T15:00:00Z',
      updatedBy: 'TS. Nguyễn Văn Bình (Hiệu trưởng)',
      changeSummary: 'Tiếp thu góp ý: Tăng cường thời lượng thực hành tính toán máy tính cầm tay tuần 11 và rà soát bám sát cấu trúc đề 2025',
      status: 'approved',
      comment: 'Đã phê duyệt. Kế hoạch đảm bảo đúng khung thời gian 35 tuần của Sở GD&ĐT và hướng dẫn CV 5512.',
      dataSnapshot: {
        title: 'Kế hoạch dạy học môn Toán Khối 12 – Năm học 2026-2027 (Phụ lục I CV 5512)',
        weeksCount: 35,
        totalPeriods: 140,
        distributionCount: 35,
      },
    },
  ],
  comments: [
    {
      id: 'pcom-01',
      authorId: 'bgh-01',
      authorName: 'TS. Nguyễn Văn Bình (Hiệu trưởng)',
      content: 'Tổ Toán cần lưu ý dành thêm tiết rèn kỹ năng giải trắc nghiệm trả lời ngắn trong các tuần 32-34 để học sinh tránh sai sót làm tròn số.',
      type: 'approval_note',
      createdAt: '2026-09-08T14:30:00Z',
    },
    {
      id: 'pcom-02',
      authorId: 'gv-02',
      authorName: 'ThS. Trần Thị Mai Phương (Tổ phó)',
      content: 'Tuần 11 đã phân phối thêm bài tập thực hành thống kê với dữ liệu khí tượng thủy văn rất trực quan.',
      type: 'comment',
      createdAt: '2026-09-07T09:15:00Z',
    },
  ],
};

export const SAMPLE_LESSON_PLAN: LessonPlan = {
  id: 'lp-01',
  teacherId: 'gv-01',
  teacherName: 'ThS. Lê Quốc Dũng',
  grade: 12,
  topicTitle: 'Ứng dụng đạo hàm giải quyết bài toán tối ưu thực tiễn',
  week: 3,
  periodCount: 2,
  classNames: ['12A1'],
  title: 'Kế hoạch bài dạy: Một số bài toán tối ưu trong đời sống và kinh tế (CV 5512)',
  status: 'approved',
  version: 2,
  isTaught: true,
  taughtDate: '2026-09-22',
  taughtClasses: ['12A1'],
  teachingStatus: 'completed',
  objectivesKnowledge: 'Học sinh mô hình hóa được bài toán thực tế thành hàm số một biến; tìm GTLN, GTNN của hàm số để tìm phương án tối ưu (chi phí nhỏ nhất, lợi nhuận lớn nhất, diện tích lớn nhất).',
  objectivesCompetence: 'Năng lực mô hình hóa toán học, giải quyết vấn đề toán học, giao tiếp và hợp tác nhóm.',
  objectivesQualities: 'Chăm chỉ, trách nhiệm với công việc nhóm, phát triển tư duy thực tiễn.',
  equipment: 'Máy chiếu, phiếu học tập nhóm, thước kẻ, máy tính cầm tay, mô hình hộp không nắp.',
  activities: [
    {
      id: 'act-1',
      name: 'Hoạt động 1: Khởi động (Tình huống thực tế)',
      objectives: 'Tạo hứng thú và gợi mở nhu cầu tìm cực trị của hàm số trong đời sống.',
      content: 'Bác nông dân có 120m lưới muốn rào một khu đất hình chữ nhật giáp bờ sông sao cho diện tích lớn nhất. Hỏi kích thước rào là bao nhiêu?',
      product: 'Dự đoán của các nhóm về kích thước khu đất; nhận thức được nhu cầu biểu diễn diện tích theo một biến.',
      implementation: 'Chuyển giao: GV chiếu hình ảnh bờ sông và đề bài.\nThực hiện: HS thảo luận cặp đôi 3 phút.\nBáo cáo: 2 HS nêu kết quả dự đoán.\nĐánh giá: GV dẫn dắt vào bài học.',
    },
    {
      id: 'act-2',
      name: 'Hoạt động 2: Hình thành kiến thức (Quy trình mô hình hóa bài toán tối ưu)',
      objectives: 'Học sinh nắm vững 3 bước giải bài toán tối ưu thực tiễn bằng đạo hàm.',
      content: 'GV hướng dẫn HS thiết lập hàm số diện tích $S(x) = x(120 - 2x)$ với $0 < x < 60$. Khảo sát tìm GTLN của $S(x)$.',
      product: 'Vở ghi của học sinh gồm 3 bước chuẩn: Lập hàm -> Khảo sát GTLN/GTNN -> Kết luận bài toán thực tiễn.',
      implementation: 'Chuyển giao: GV phát phiếu học tập số 1.\nThực hiện: HS làm việc cá nhân 5 phút sau đó trao đổi nhóm.\nBáo cáo: Đại diện nhóm 1 lên bảng trình bày.\nĐánh giá: GV chốt kiến thức.',
    },
    {
      id: 'act-3',
      name: 'Hoạt động 3: Luyện tập (Giải bài toán chi phí)',
      objectives: 'Áp dụng vào bài toán làm thùng chứa hình trụ có thể tích cho trước sao cho tốn ít vật liệu nhất.',
      content: 'Phiếu học tập số 2: Tìm bán kính đáy $R$ và chiều cao $h$ của lon nước ngọt thể tích $330\\text{ ml}$ sao cho diện tích toàn phần nhỏ nhất.',
      product: 'Bài làm trên bảng nhóm của 4 tổ.',
      implementation: 'Tổ chức cho 4 nhóm thi đua giải toán. GV quan sát và hỗ trợ các nhóm gặp khó khăn về công thức hình học.',
    },
    {
      id: 'act-4',
      name: 'Hoạt động 4: Vận dụng (Dự án nhỏ)',
      objectives: 'Vận dụng kiến thức thiết kế bao bì tiết kiệm nguyên liệu cho câu lạc bộ STEM của trường.',
      content: 'Thiết kế hộp đựng bánh quy từ một tấm bìa cứng vuông cạnh 30cm bằng cách cắt 4 góc.',
      product: 'Mẫu hộp bánh bằng bìa do HS gấp tại nhà kèm bản tính toán thể tích cực đại.',
      implementation: 'Giao nhiệm vụ về nhà cho các nhóm nộp vào tiết sinh hoạt chuyên môn tuần sau.',
    },
  ],
  versionHistory: [
    {
      version: 1,
      updatedAt: '2026-09-05T08:30:00Z',
      updatedBy: 'ThS. Lê Quốc Dũng',
      changeSummary: 'Soạn thảo bản đầu tiên theo khung 4 hoạt động CV 5512',
      status: 'submitted',
      comment: 'Kính gửi Tổ phó chuyên môn góp ý bài toán rào đất thực tế.',
      dataSnapshot: {
        title: 'Kế hoạch bài dạy: Một số bài toán tối ưu (v1)',
        activitiesCount: 4,
      },
    },
    {
      version: 2,
      updatedAt: '2026-09-09T16:00:00Z',
      updatedBy: 'ThS. Lê Quốc Dũng',
      changeSummary: 'Bổ sung nhấn mạnh điều kiện biến số $0 < x < 60$ ở HĐ2 theo góp ý của ThS. Mai Phương',
      status: 'approved',
      comment: 'Đã hoàn thiện và phê duyệt cho phép giảng dạy tại lớp 12A1.',
      dataSnapshot: {
        title: 'Kế hoạch bài dạy: Một số bài toán tối ưu trong đời sống và kinh tế (CV 5512)',
        activitiesCount: 4,
      },
    },
  ],
  comments: [
    {
      id: 'c-1',
      authorId: 'gv-02',
      authorName: 'ThS. Trần Thị Mai Phương',
      sectionId: 'Hoạt động 2',
      content: 'Nên nhấn mạnh điều kiện biến số $0 < x < 60$ vì học sinh thường quên đối chiếu điều kiện thực tế khi làm bài trắc nghiệm.',
      reply: 'Đã bổ sung câu hỏi bẫy về điều kiện biến số trong phiếu học tập.',
      isResolved: true,
      createdAt: '2026-09-09T10:00:00Z',
    },
  ],
  approvedBy: 'ThS. Trần Thị Mai Phương (Tổ phó)',
  updatedAt: '2026-09-09T16:00:00Z',
};

export const SAMPLE_OBSERVATIONS: ObservationRecord[] = [
  {
    id: 'obs-01',
    observerId: 'gv-02',
    observerName: 'ThS. Trần Thị Mai Phương',
    teacherId: 'gv-01',
    teacherName: 'ThS. Lê Quốc Dũng',
    className: '12A1',
    period: 2,
    date: '2026-09-15',
    lessonName: 'Một số bài toán tối ưu trong đời sống và kinh tế',
    lessonPlanId: 'lp-01',
    activitiesObservations: [
      {
        activityName: 'Hoạt động 1: Khởi động',
        studentActions: 'Học sinh hào hứng thảo luận, nhiều em vẽ nhanh sơ đồ bờ sông vào nháp.',
        difficultiesNoticed: 'Một vài học sinh ban đầu rào cả 4 cạnh thay vì chỉ 3 cạnh.',
        teacherSupport: 'Giáo viên nhấn mạnh lại từ khóa \"bờ sông không cần rào\", chiếu hình ảnh trực quan giúp các em sửa sai kịp thời.',
      },
      {
        activityName: 'Hoạt động 2: Hình thành kiến thức',
        studentActions: 'Hầu hết các nhóm thiết lập được hàm $S(x)$. Nhóm 3 sử dụng BĐT Cauchy thay vì đạo hàm.',
        difficultiesNoticed: 'Hai học sinh bàn cuối gặp khó khăn khi tìm tập xác định của biến số $x$.',
        teacherSupport: 'Giáo viên khuyến khích cách giải Cauchy của nhóm 3, đồng thời hướng dẫn nhóm bàn cuối liên hệ độ dài đoạn thẳng với điều kiện $x > 0$ và $120 - 2x > 0$.',
      },
    ],
    generalEvaluation: 'Tiết dạy chuẩn bị chu đáo, đúng định hướng phát triển phẩm chất và năng lực học sinh theo CV 5512. Học sinh chủ động làm việc và tranh luận sôi nổi.',
    lessonsLearned: 'Cần dành nhiều thời gian hơn cho học sinh tự phát hiện mối liên hệ thực tiễn trước khi đưa ra công thức đại số.',
    teacherFeedback: 'Cảm ơn góp ý của đồng chí Phương. Tiết sau tôi sẽ để các em tự đo đạc trên mô hình thực tế.',
    ratingEnabled: false,
    status: 'reviewed',
    updatedAt: '2026-09-15T16:30:00Z',
  },
];

export const SAMPLE_MEETINGS: Meeting[] = [
  {
    id: 'meet-01',
    title: 'Sinh hoạt chuyên môn Tổ Toán – Tháng 9/2026 (Triển khai kế hoạch năm học & Nghiên cứu bài học Khối 12)',
    type: 'lesson_study',
    date: '2026-09-16',
    location: 'Văn phòng Tổ Toán (Phòng A203)',
    isOnline: false,
    chairPerson: 'ThS. Lê Quốc Dũng (Tổ trưởng)',
    secretary: 'Cô Phạm Thùy Linh',
    attendees: ['Lê Quốc Dũng', 'Trần Thị Mai Phương', 'Hoàng Văn Nam', 'Phạm Thùy Linh', 'Đặng Minh Tuấn', 'Vũ Ngọc Ánh'],
    absentees: [],
    content: `1. Đánh giá tiến độ thực hiện chương trình tuần 1-2: Cả 3 khối 10, 11, 12 đều thực hiện đúng tiến độ, không có lớp nào bị chậm quá 1 tiết.\n2. Thảo luận sinh hoạt chuyên môn theo nghiên cứu bài học: Đồng chí Dũng báo cáo kinh nghiệm dạy minh họa chuyên đề Tối ưu hóa tại lớp 12A1.\n3. Rà soát ngân hàng câu hỏi định dạng Tốt nghiệp 2025: Mỗi giáo viên được giao biên soạn bổ sung 10 câu hỏi dạng Đúng/Sai và Trả lời ngắn trước ngày 30/09.\n4. Kế hoạch bồi dưỡng HSG và phụ đạo học sinh còn yếu.`,
    memberOpinions: [
      { author: 'Trần Thị Mai Phương', content: 'Dạng câu hỏi Đúng/Sai 4 ý cần được tăng cường luyện tập ngay trên lớp vì học sinh còn tâm lý lúng túng khi chấm điểm theo bậc lũy tiến.' },
      { author: 'Đặng Minh Tuấn', content: 'Cần chia sẻ các applet GeoGebra dùng chung lên thư viện tài liệu của tổ để giáo viên toàn tổ có thể tái sử dụng.' },
    ],
    conclusions: 'Thống nhất kế hoạch dạy học của tổ; phân công đồng chí Nam chuẩn bị bài dạy minh họa khối 10 tuần 6; chốt ngân hàng câu hỏi đợt 1 vào ngày 30/9.',
    tasks: [
      { id: 't-1', title: 'Hoàn thiện ngân hàng câu hỏi dạng Đúng/Sai Khối 12', assigneeName: 'ThS. Đặng Minh Tuấn', deadline: '2026-09-30', status: 'in_progress' },
      { id: 't-2', title: 'Soạn giáo án minh họa nghiên cứu bài học Khối 10', assigneeName: 'Thầy Hoàng Văn Nam', deadline: '2026-10-05', status: 'pending' },
    ],
    status: 'finalized',
    lockedAt: '2026-09-16T17:30:00Z',
    updatedAt: '2026-09-16T17:30:00Z',
  },
];


export const SAMPLE_SPECIAL_TOPICS: SpecialTopic[] = [
  {
    id: 'st-01',
    title: 'Ứng dụng phần mềm GeoGebra và trí tuệ nhân tạo trong dạy học Hình học không gian 12',
    level: 'To',
    reporterName: 'ThS. Trần Thị Mai Phương',
    date: '2026-09-22',
    materialsSummary: 'Tập hợp 15 applet 3D mô phỏng toạ độ Oxyz và các mặt nón, trụ, cầu.',
    results: 'Được toàn tổ xếp loại Xuất sắc, đưa vào thư viện dùng chung cho năm học 2026-2027.',
    geogebraOrSoftware: 'GeoGebra 3D Calculator',
    updatedAt: '2026-09-22T16:00:00Z',
  },
];

export const SAMPLE_TRAININGS: TrainingRecord[] = [
  {
    id: 'tr-01',
    teacherId: 'gv-03',
    teacherName: 'Thầy Hoàng Văn Nam',
    moduleName: 'Mô-đun 4: Xây dựng kế hoạch dạy học và giáo dục theo hướng phát triển phẩm chất, năng lực học sinh môn Toán',
    hours: 32,
    status: 'Đã hoàn thành',
    certificateUrl: 'https://taphuan.csdl.edu.vn/cert/mod4-namhv',
    academicYear: '2026-2027',
    updatedAt: '2026-09-10T11:00:00Z',
  },
];

export const SAMPLE_INITIATIVES: InitiativeRecord[] = [
  {
    id: 'init-01',
    teacherName: 'ThS. Lê Quốc Dũng',
    title: 'Giải pháp nâng cao năng lực mô hình hóa toán học cho học sinh lớp 12 qua các bài toán tối ưu kinh tế',
    progress: 'Đang thử nghiệm',
    departmentFeedback: 'Đề tài mang tính thực tiễn cao, bám sát yêu cầu cần đạt của Chương trình GDPT 2018.',
    year: '2026-2027',
  },
];


export const SAMPLE_SKKN_TOPICS: SkknTopic[] = [
  {
    id: 'skkn-01',
    title: 'Giải pháp nâng cao năng lực mô hình hóa toán học cho học sinh lớp 12 qua các bài toán tối ưu kinh tế',
    academicYear: '2026-2027',
    evaluationLevel: 'Cấp Ngành (Xuất sắc)',
    abstract: 'Đề tài xây dựng hệ thống 24 bài toán tối ưu thực tiễn gắn với đời sống, tích hợp mô phỏng đồ thị trực quan, giúp học sinh nắm vững các bước lập hàm số và biện luận cực trị.',
    authorId: 'gv-01',
    authorName: 'ThS. Lê Quốc Dũng',
    scope: 'Toàn tỉnh',
    createdAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'skkn-02',
    title: 'Ứng dụng phần mềm GeoGebra 3D Calculator trong dạy học chuyên đề Phương pháp tọa độ trong không gian',
    academicYear: '2026-2027',
    evaluationLevel: 'Cấp Trường (Loại A)',
    abstract: 'Thiết kế 18 mô hình 3D động về vectơ, mặt phẳng, mặt cầu và đường thẳng trong Oxyz, giúp học sinh phát triển năng lực tưởng tượng không gian.',
    authorId: 'gv-02',
    authorName: 'ThS. Trần Thị Mai Phương',
    scope: 'Cụm chuyên môn',
    createdAt: '2026-09-10T09:00:00Z',
  },
];

export const SAMPLE_SPECIAL_TOPICS_ENRICHED: SpecialTopic[] = [
  {
    id: 'topic-01',
    title: 'Kỹ thuật giải nhanh bài toán cực trị hình học Oxyz bằng phương pháp vectơ và tọa độ',
    grade: 12,
    type: 'tot_nghiep',
    authorId: 'gv-01',
    authorName: 'ThS. Lê Quốc Dũng',
    targetStudents: 'Học sinh lớp 12 ôn thi tốt nghiệp THPT, mục tiêu 8+',
    totalPeriods: 12,
    description: 'Tổng hợp các kỹ thuật sử dụng tích có hướng, khoảng cách và phương pháp hàm số để giải quyết bài toán cực trị không gian.',
    attachmentsCount: 3,
    level: 'To',
    reporterName: 'ThS. Lê Quốc Dũng',
    date: '2026-09-15',
    materialsSummary: '3 chuyên đề + 50 bài tập có lời giải chi tiết',
    results: 'Áp dụng tốt cho 3 lớp 12',
    createdAt: '2026-09-15T08:00:00Z',
    updatedAt: '2026-09-15T08:00:00Z',
  },
  {
    id: 'topic-02',
    title: 'Bồi dưỡng học sinh giỏi: Bất đẳng thức tích phân và phương trình hàm',
    grade: 12,
    type: 'hsg',
    authorId: 'gv-02',
    authorName: 'ThS. Trần Thị Mai Phương',
    targetStudents: 'Đội tuyển HSG cấp tỉnh môn Toán',
    totalPeriods: 24,
    description: 'Chuyên đề chuyên sâu về bất đẳng thức Cauchy-Schwarz dạng tích phân, kỹ thuật tích phân từng phần nâng cao.',
    attachmentsCount: 5,
    level: 'Cum',
    reporterName: 'ThS. Trần Thị Mai Phương',
    date: '2026-09-20',
    materialsSummary: 'Tập hợp đề thi HSG các năm',
    createdAt: '2026-09-20T08:00:00Z',
    updatedAt: '2026-09-20T08:00:00Z',
  },
  {
    id: 'topic-03',
    title: 'Phụ đạo học sinh: Củng cố kỹ năng giải phương trình, bất phương trình mũ và logarit',
    grade: 11,
    type: 'phu_dao',
    authorId: 'gv-03',
    authorName: 'Thầy Hoàng Văn Nam',
    targetStudents: 'Học sinh cần tăng cường kỹ năng tính toán và nhận diện nghiệm ngoại lai',
    totalPeriods: 8,
    description: 'Rèn luyện quy tắc đổi cơ số, tìm điều kiện xác định và tránh sai lầm thường gặp khi giải phương trình logarit.',
    attachmentsCount: 2,
    level: 'To',
    reporterName: 'Thầy Hoàng Văn Nam',
    date: '2026-09-25',
    materialsSummary: 'Phiếu bài tập theo từng mức độ nhận biết - thông hiểu',
    createdAt: '2026-09-25T08:00:00Z',
    updatedAt: '2026-09-25T08:00:00Z',
  },
];

const q = (
  id: string,
  grade: 10 | 11 | 12,
  type: Question['type'],
  difficulty: Question['difficulty'],
  topic: string,
  content: string,
  answer: string,
  options?: string[],
  authorId = 'gv-01',
  authorName = 'ThS. Lê Quốc Dũng',
): Question => ({
  id,
  grade,
  type,
  difficulty,
  topic,
  content,
  answer,
  options,
  authorId,
  authorName,
  status: 'approved',
  createdAt: '2026-09-12T08:00:00Z',
});

export const SAMPLE_QUESTIONS: Question[] = [
  q('q-01', 12, 'mcq', 'NB', 'Ứng dụng đạo hàm', 'Hàm số $y = x^3 - 3x + 1$ đạt cực đại tại điểm nào?', 'A', ['$x = -1$', '$x = 1$', '$x = 0$', '$x = 3$']),
  q('q-02', 12, 'mcq', 'TH', 'Ứng dụng đạo hàm', 'Giá trị lớn nhất của hàm số $f(x) = -x^2 + 4x$ trên đoạn $[0; 3]$ bằng', 'C', ['$3$', '$0$', '$4$', '$5$']),
  q('q-03', 12, 'mcq', 'NB', 'Nguyên hàm – Tích phân', 'Nguyên hàm của hàm số $f(x) = 2x$ là', 'B', ['$2$', '$x^2 + C$', '$2x^2 + C$', '$\\frac{x^2}{2} + C$']),
  q('q-04', 12, 'mcq', 'TH', 'Nguyên hàm – Tích phân', 'Tích phân $\\int_0^1 3x^2\\,dx$ bằng', 'D', ['$3$', '$0$', '$\\frac{1}{3}$', '$1$']),
  q('q-05', 12, 'mcq', 'NB', 'Phương pháp tọa độ trong không gian', 'Trong không gian $Oxyz$, mặt phẳng $(P): x - 2y + 2z - 3 = 0$ có một vectơ pháp tuyến là', 'A', ['$(1; -2; 2)$', '$(1; 2; 2)$', '$(-2; 2; -3)$', '$(1; -2; -3)$']),
  q('q-06', 12, 'mcq', 'TH', 'Phương pháp tọa độ trong không gian', 'Khoảng cách từ $O$ đến mặt phẳng $(P): 2x + y - 2z + 6 = 0$ bằng', 'B', ['$1$', '$2$', '$3$', '$6$']),
  q('q-07', 12, 'mcq', 'NB', 'Thống kê', 'Khoảng biến thiên của mẫu số liệu $2; 5; 7; 9; 12$ là', 'C', ['$7$', '$9$', '$10$', '$12$']),
  q('q-08', 12, 'mcq', 'VD', 'Ứng dụng đạo hàm', 'Có bao nhiêu giá trị nguyên của $m$ để hàm số $y = x^3 - 3mx^2 + 3x$ đồng biến trên $\\mathbb{R}$?', 'C', ['$1$', '$2$', '$3$', '$4$']),
  q('q-09', 12, 'true_false', 'TH', 'Ứng dụng đạo hàm', 'Cho hàm số $f(x) = x^3 - 3x^2$. Xét tính đúng/sai của các mệnh đề sau:', 'ĐSĐS', [
    "$f'(x) = 3x^2 - 6x$",
    'Hàm số đồng biến trên khoảng $(0; 2)$',
    'Giá trị cực tiểu của hàm số là $-4$',
    'Đồ thị hàm số có hai điểm cực trị nằm cùng phía trục hoành',
  ]),
  q('q-10', 12, 'true_false', 'VD', 'Phương pháp tọa độ trong không gian', 'Trong không gian $Oxyz$ cho $A(1;0;0)$, $B(0;2;0)$, $C(0;0;3)$. Xét tính đúng/sai:', 'ĐĐSĐ', [
    'Phương trình mặt phẳng $(ABC)$ là $\\frac{x}{1} + \\frac{y}{2} + \\frac{z}{3} = 1$',
    '$\\overrightarrow{AB} = (-1; 2; 0)$',
    'Tam giác $ABC$ vuông tại $A$',
    'Thể tích tứ diện $OABC$ bằng $1$',
  ]),
  q('q-11', 12, 'short_answer', 'VD', 'Ứng dụng đạo hàm', 'Một người rào mảnh vườn hình chữ nhật sát bờ sông bằng $120\\,m$ lưới (không rào phía bờ sông). Diện tích lớn nhất của mảnh vườn là bao nhiêu $m^2$?', '1800'),
  q('q-12', 12, 'short_answer', 'TH', 'Nguyên hàm – Tích phân', 'Tính diện tích hình phẳng giới hạn bởi $y = x^2$ và $y = 2x$.', '1.33'),
  q('q-13', 11, 'mcq', 'NB', 'Hàm số mũ và logarit', 'Tập xác định của hàm số $y = \\log_2(x - 1)$ là', 'B', ['$\\mathbb{R}$', '$(1; +\\infty)$', '$[1; +\\infty)$', '$(0; +\\infty)$'], 'gv-03', 'Thầy Hoàng Văn Nam'),
  q('q-14', 11, 'mcq', 'TH', 'Hàm số mũ và logarit', 'Nghiệm của phương trình $3^{x-1} = 27$ là', 'D', ['$x = 2$', '$x = 3$', '$x = 5$', '$x = 4$'], 'gv-03', 'Thầy Hoàng Văn Nam'),
  q('q-15', 10, 'mcq', 'NB', 'Mệnh đề và tập hợp', 'Cho $A = \\{1; 2; 3\\}$, $B = \\{2; 3; 4\\}$. Tập $A \\cap B$ là', 'A', ['$\\{2; 3\\}$', '$\\{1; 4\\}$', '$\\{1; 2; 3; 4\\}$', '$\\emptyset$'], 'gv-04', 'Cô Phạm Thùy Linh'),
  q('q-16', 10, 'short_answer', 'TH', 'Hàm số bậc hai', 'Tìm hoành độ đỉnh của parabol $y = x^2 - 6x + 5$.', '3', undefined, 'gv-04', 'Cô Phạm Thùy Linh'),
];

export const SAMPLE_DOCUMENTS: SharedDocument[] = [
  {
    id: 'doc-01',
    title: 'Công văn 5512/BGDĐT-GDTrH – Hướng dẫn xây dựng và tổ chức thực hiện kế hoạch giáo dục',
    url: 'https://moet.gov.vn',
    category: 'van_ban',
    description: 'Văn bản gốc kèm các Phụ lục I, II, III, IV.',
    grade: 0,
    uploaderId: 'gv-01',
    uploaderName: 'ThS. Lê Quốc Dũng',
    createdAt: '2026-09-02T08:00:00Z',
  },
  {
    id: 'doc-02',
    title: 'Thư viện applet GeoGebra 3D – Phương pháp tọa độ trong không gian',
    url: 'https://www.geogebra.org',
    category: 'hoc_lieu',
    description: '15 mô hình động dùng cho chương Oxyz lớp 12.',
    grade: 12,
    uploaderId: 'gv-02',
    uploaderName: 'ThS. Trần Thị Mai Phương',
    createdAt: '2026-09-18T08:00:00Z',
  },
];
