import React,{useMemo,useState} from 'react';
import { useApp } from '../../context/AppContext';
import { pathId,pushRoute } from '../../utils/deepLink';
import { Clock3, FileClock, Link2, ShieldCheck } from 'lucide-react';
export const AuditTrailModule:React.FC=()=>{
 const {auditLogs,departmentPlans,teacherPlans,lessonPlans,setNotification}=useApp(); const deep=pathId('audit');
 const entities=useMemo(()=>[...departmentPlans.map(x=>({id:x.id,label:`KH tổ: ${x.title}`,versions:x.versionHistory||[]})),...teacherPlans.map(x=>({id:x.id,label:`KHGV: ${x.teacherName} – ${x.title}`,versions:[]})),...lessonPlans.map(x=>({id:x.id,label:`Giáo án: ${x.teacherName} – ${x.title||x.topicTitle}`,versions:x.versionHistory||[]}))],[departmentPlans,teacherPlans,lessonPlans]);
 const [target,setTarget]=useState(deep||'all'); const logs=useMemo(()=>auditLogs.filter(l=>target==='all'||l.targetId===target).sort((a,b)=>b.timestamp.localeCompare(a.timestamp)),[auditLogs,target]); const entity=entities.find(e=>e.id===target);
 const copy=async()=>{if(target!=='all')pushRoute('audit-trail',target,true); await navigator.clipboard.writeText(window.location.href);setNotification({type:'success',message:'Đã sao chép deep-link nhật ký.'});};
 return <div className="space-y-5"><div className="bg-white border rounded-xl p-5 flex flex-wrap justify-between gap-3"><div><div className="flex gap-2 items-center"><ShieldCheck className="w-5 h-5 text-indigo-600"/><h1 className="text-xl font-bold">Lịch sử phiên bản & Audit</h1></div><p className="text-xs text-slate-500 mt-1">Dòng thời gian dễ đọc, lọc theo hồ sơ và có deep-link để kiểm tra trực tiếp.</p></div><div className="flex gap-2"><select value={target} onChange={e=>{setTarget(e.target.value);pushRoute('audit-trail',e.target.value==='all'?undefined:e.target.value)}} className="border rounded-lg px-3 py-2 text-xs bg-white max-w-sm"><option value="all">Tất cả hoạt động</option>{entities.map(e=><option key={e.id} value={e.id}>{e.label}</option>)}</select><button onClick={copy} className="border rounded-lg px-3 py-2 text-xs font-semibold flex items-center gap-1"><Link2 className="w-3.5 h-3.5"/>Sao chép link</button></div></div>
 <div className="grid lg:grid-cols-3 gap-5"><div className="lg:col-span-2 bg-white border rounded-xl p-5"><h2 className="font-bold text-sm mb-4 flex items-center gap-2"><Clock3 className="w-4 h-4"/>Dòng thời gian audit ({logs.length})</h2><div className="space-y-0">{logs.length?logs.map((l,i)=><div key={l.id} className="relative pl-7 pb-5"><span className="absolute left-1.5 top-1 w-2.5 h-2.5 rounded-full bg-blue-600"/>{i<logs.length-1&&<span className="absolute left-[10px] top-3 h-full border-l border-slate-200"/>}<div className="text-xs font-bold">{l.action}</div><div className="text-[11px] text-slate-500">{new Date(l.timestamp).toLocaleString('vi-VN')} · {l.actorName}</div><div className="text-xs text-slate-700 mt-1 bg-slate-50 rounded p-2">{l.details}</div></div>):<div className="text-xs text-slate-500">Không có bản ghi phù hợp.</div>}</div></div>
 <div className="bg-white border rounded-xl p-5"><h2 className="font-bold text-sm mb-4 flex items-center gap-2"><FileClock className="w-4 h-4"/>Phiên bản hồ sơ</h2>{target==='all'?<p className="text-xs text-slate-500">Chọn một kế hoạch/giáo án để xem lịch sử phiên bản.</p>:entity?.versions?.length?<div className="space-y-3">{[...entity.versions].reverse().map((v:any)=><div key={`${v.version}-${v.updatedAt}`} className="border rounded-lg p-3"><div className="text-xs font-bold">Phiên bản {v.version} · {v.status}</div><div className="text-[11px] text-slate-500">{new Date(v.updatedAt).toLocaleString('vi-VN')} · {v.updatedBy}</div><div className="text-xs mt-1">{v.changeSummary||v.summary||'Cập nhật hồ sơ'}</div></div>)}</div>:<p className="text-xs text-slate-500">Hồ sơ này chưa lưu versionHistory riêng; các thay đổi vẫn có thể xem trong audit ở bên trái.</p>}</div></div></div>
}
