import React,{useMemo,useState} from 'react';
import { useApp } from '../../context/AppContext';
import { STATUS_CLS, STATUS_TEXT, TERM_TEXT, teacherStandards, type StandardTerm } from '../../utils/standards';
import { pathId, pushRoute } from '../../utils/deepLink';
import { Award, BookOpen, CalendarCheck, ClipboardCheck, Eye, Link2, UserRound } from 'lucide-react';
export const Teacher360Module:React.FC=()=>{
 const {activeMember,permissions,allMembers,assignments,teacherPlans,lessonPlans,observations,meetings,trainings,workTasks,auditLogs,setNotification,config}=useApp();
 const [term,setTerm]=useState<StandardTerm>(config.currentTerm||'HK1');
 const initial=pathId('teachers'); const [id,setId]=useState(initial&&allMembers.some(m=>m.id===initial)?initial:(allMembers[0]?.id||''));
 // Giáo viên chỉ xem hồ sơ của chính mình (không so sánh, không xếp hạng)
 const canViewOthers=permissions.isLeader||activeMember.role==='principal';
 const m=canViewOthers?(allMembers.find(x=>x.id===id)||allMembers[0]):(allMembers.find(x=>x.id===activeMember.id)||activeMember);
 const kpi=useMemo(()=>m?teacherStandards(m,{teacherPlans,lessonPlans,observations,meetings,trainings,workTasks,members:allMembers},config,term):null,[m,teacherPlans,lessonPlans,observations,meetings,trainings,workTasks,allMembers,config,term]);
 if(!m||!kpi)return <div className="p-6 text-sm text-slate-500">Chưa có giáo viên.</div>;
 const asg=assignments.filter(a=>a.teacherId===m.id&&a.academicYear===config.academicYear); const logs=auditLogs.filter(l=>l.actorId===m.id||l.targetId===m.id).sort((a,b)=>b.timestamp.localeCompare(a.timestamp)).slice(0,8);
 const copy=async()=>{pushRoute('teacher-360',m.id,true); await navigator.clipboard.writeText(window.location.href); setNotification({type:'success',message:'Đã sao chép liên kết hồ sơ 360°.'});};
 return <div className="space-y-5">
  <div className="bg-white border border-slate-200 rounded-xl p-5 flex flex-wrap justify-between gap-4"><div><div className="flex items-center gap-2"><UserRound className="w-5 h-5 text-blue-600"/><h1 className="text-xl font-bold">{canViewOthers?'Hồ sơ 360° giáo viên':'Hồ sơ của tôi'}</h1></div><p className="text-xs text-slate-500 mt-1">Một điểm nhìn: phân công → hồ sơ → giáo án → dự giờ → nhiệm vụ → tiến độ hồ sơ → dấu vết.</p></div><div className="flex gap-2">{canViewOthers&&<><select value={m.id} onChange={e=>{setId(e.target.value);pushRoute('teacher-360',e.target.value)}} className="border rounded-lg px-3 py-2 text-xs bg-white">{allMembers.map(x=><option key={x.id} value={x.id}>{x.displayName}</option>)}</select><button onClick={copy} className="border rounded-lg px-3 py-2 text-xs font-semibold flex items-center gap-1"><Link2 className="w-3.5 h-3.5"/>Sao chép link</button></>}</div></div>
  <div className="bg-white border rounded-xl p-4 text-xs space-y-2"><div className="flex flex-wrap items-center gap-3"><strong>Năm học {config.academicYear}</strong><div className="flex gap-1 bg-slate-100 p-1 rounded-lg">{(['HK1','HK2','CaNam'] as StandardTerm[]).map(t=><button key={t} onClick={()=>setTerm(t)} className={`px-3 py-1 rounded-md font-semibold ${term===t?'bg-white shadow-xs text-blue-700':'text-slate-600'}`}>{TERM_TEXT[t]}</button>)}</div><span className="text-slate-500">{new Date(kpi.start+'T00:00:00').toLocaleDateString('vi-VN')} – {new Date(kpi.end+'T00:00:00').toLocaleDateString('vi-VN')}</span></div><p>Đối chiếu minh chứng với <b>định mức tối thiểu của tổ</b> (sửa trong 12. Cài đặt). Mỗi nhóm chỉ ghi Đạt / Chưa đạt / Chưa đến hạn – không quy ra điểm, không xếp hạng. Còn trong kỳ mà chưa đủ thì ghi "Chưa đến hạn"; nhóm tổ không đặt định mức thì không tính.</p>{kpi.unassignedTasks>0&&<p className="text-amber-700">Có {kpi.unassignedTasks} nhiệm vụ trong biên bản chưa xác định duy nhất người thực hiện; chưa đưa vào đối chiếu.</p>}</div>
  <div className="grid md:grid-cols-4 gap-3"><div className={`md:col-span-1 rounded-xl p-5 text-white ${kpi.overall==='chua_dat'?'bg-rose-600':kpi.overall==='dat'?'bg-emerald-600':'bg-blue-600'}`}><div className="text-xs opacity-80">Định mức {TERM_TEXT[term]}</div><div className="text-4xl font-black mt-2">{kpi.counted?`${kpi.met}/${kpi.counted}`:'—'}</div><div className="text-xs mt-1">{kpi.counted?'nhóm đã đạt':'Tổ chưa đặt định mức'}</div><div className="mt-2 inline-block px-2 py-0.5 rounded bg-white/20 text-[11px] font-bold">{STATUS_TEXT[kpi.overall]}</div><div className="border-t border-white/30 mt-4 pt-3 text-xs space-y-1"><div className="font-bold">{m.displayName}</div><div>{m.subject}</div><div>{m.qualifications||'Chưa cập nhật trình độ'}</div><div>{[...new Set(asg.map(a=>a.className).filter(Boolean))].join(', ')||'Chưa phân công lớp'}</div></div></div>
   <div className="md:col-span-3 grid sm:grid-cols-2 lg:grid-cols-5 gap-3">{kpi.groups.map((g,i)=>{const I=[CalendarCheck,BookOpen,Eye,ClipboardCheck,Award][i];return <div key={g.key} className="bg-white border rounded-xl p-4"><I className="w-4 h-4 text-blue-600"/><div className="text-xs font-bold mt-2">{g.label}</div><div className={`inline-block mt-2 px-2 py-0.5 rounded border text-[11px] font-bold whitespace-nowrap ${STATUS_CLS[g.status]}`}>{STATUS_TEXT[g.status]}</div><div className="text-[11px] text-slate-500 mt-2">{g.detail}</div></div>})}</div></div>
  <div className="grid lg:grid-cols-2 gap-5"><div className="bg-white border rounded-xl p-5"><h2 className="font-bold text-sm mb-3">Minh chứng trong kỳ</h2><div className="space-y-3">{kpi.groups.map(g=><details key={g.key} className="border rounded-lg p-3"><summary className="cursor-pointer text-xs font-semibold flex justify-between gap-2"><span>{g.label}</span><span className={`px-2 rounded border text-[10px] ${STATUS_CLS[g.status]}`}>{g.detail}</span></summary><div className="mt-2 text-[11px] text-slate-600">{g.refs.length?g.refs.map((r,i)=><div key={i} className="py-1 border-t first:border-0">• {r}</div>):<i>Chưa có minh chứng trong kỳ.</i>}</div></details>)}</div></div>
   <div className="bg-white border rounded-xl p-5"><h2 className="font-bold text-sm mb-3">Hoạt động & dấu vết gần đây</h2>{logs.length?<div className="space-y-2">{logs.map(l=><div key={l.id} className="border-l-2 border-blue-200 pl-3 py-1"><div className="text-xs font-semibold">{l.action}</div><div className="text-[11px] text-slate-500">{new Date(l.timestamp).toLocaleString('vi-VN')} · {l.details}</div></div>)}</div>:<div className="text-xs text-slate-500">Chưa có nhật ký liên quan.</div>}</div></div>
 </div>
}
